In [ ]:
#1. Import the numpy package under the name np

In [1]:
import numpy as np

In [ ]:
# 2. Print the numpy version and the configuration

In [4]:
print(np.__version__)
np.show_config()

1.23.2
openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBO

In [ ]:
# 3. Create a null vector of size 10 

In [5]:
X = np.zeros(10)
print(X)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# 4. How to find the memory size of any array

In [7]:
X = np.zeros((10,10))
print("%d bytes" % (X.size * X.itemsize))

800 bytes


In [ ]:
# 5. How to get the documentation of the numpy add function from the command line?

In [ ]:
# 6. Create a null vector of size 10 but the fifth value which is 1

In [10]:
X = np.zeros(10)
X[4] = 1
print(X)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# 7. Create a vector with values ranging from 10 to 49

In [11]:
Y = np.arange(10,50)
print(Y)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
# 8. Reverse a vector (first element becomes last)   


Y = np.arange(50)
Y = Y[::-1]
print(Y)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [14]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8


Z = np.arange(9).reshape(3, 3)
print(Z)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0] 

X = np.nonzero([1,2,0,0,4,0])
print(X)

(array([0, 1, 4], dtype=int64),)


In [16]:
#Create a 3x3 identity matrix

Y = np.eye(3)
print(Y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
# 12. Create a 3x3x3 array with random values


X = np.random.random((3,3,3))
print(X)

[[[0.10405957 0.65611907 0.48058811]
  [0.68548751 0.14131247 0.22347389]
  [0.31614574 0.00150307 0.1937289 ]]

 [[0.45266803 0.32749813 0.16711582]
  [0.16347588 0.01126094 0.18066282]
  [0.82528651 0.11790462 0.0831499 ]]

 [[0.4074784  0.05610233 0.15761668]
  [0.71190292 0.99135949 0.9532746 ]
  [0.26627383 0.93325568 0.35411813]]]


In [18]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values

X = np.random.random((10,10))
Xmin, Xmax = X.min(), X.max()
print(Xmin, Xmax)

0.01919367543360273 0.9999516496221849


In [19]:
# 14. Create a random vector of size 30 and find the mean value

Z = np.random.random(30)
M = Z.mean()
print(M)

0.3547684701056354


In [20]:
# 15. Create a 2d array with 1 on the border and 0 inside

Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [21]:
# 16. How to add a border (filled with 0's) around an existing array?

Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [23]:
# 17. What is the result of the following expression?

#0 * np.nan
#np.nan == np.nan
#np.inf > np.nan
#np.nan - np.nan
#np.nan in set([np.nan])
#0.3 == 3 * 0.1

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [24]:
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

Y = np.diag(1+np.arange(4),k=-1)
print(Y)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [25]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern

Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [27]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

print(np.unravel_index(99,(6,7,8)))



(1, 5, 3)


In [28]:
# 21. Create a checkerboard 8x8 matrix using the tile function

Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [29]:
# 22. Normalize a 5x5 random matrix

X = np.random.random((5,5))
X = (Z - np.mean (Z)) / (np.std (Z))
print(X)

[[-1.  1. -1.  1. -1.  1. -1.  1.]
 [ 1. -1.  1. -1.  1. -1.  1. -1.]
 [-1.  1. -1.  1. -1.  1. -1.  1.]
 [ 1. -1.  1. -1.  1. -1.  1. -1.]
 [-1.  1. -1.  1. -1.  1. -1.  1.]
 [ 1. -1.  1. -1.  1. -1.  1. -1.]
 [-1.  1. -1.  1. -1.  1. -1.  1.]
 [ 1. -1.  1. -1.  1. -1.  1. -1.]]


In [31]:
# 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

In [32]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

X = np.ones((5,3)) @ np.ones((3,2))
print(X)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [33]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [34]:
# 26. What is the output of the following script?

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [ ]:
# 27. Consider an integer vector Z, which of these expressions are legal?

In [38]:
print(4**4)
print(2 << 4 >> 2)
print(4 <- 4)
print(1j*4)
print(4/1/1)
print(4<4>4)

256
8
False
4j
4.0
False


In [39]:
# 28. What are the result of the following expressions? 

#np.array(0) / np.array(0)
#np.array(0) // np.array(0)
#np.array([np.nan]).astype(int).astype(float)


print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\mithu\AppData\Local\Temp\ipykernel_24500\2113895029.py:8: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\mithu\AppData\Local\Temp\ipykernel_24500\2113895029.py:9: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [40]:
# 29. How to round away from zero a float array ?

print(np.copysign(np.ceil(np.abs(Z)), Z))

[ 0.  1.  2.  3. -4. -5. -6. -7.  8.  9. 10.]


In [48]:
# 30. How to find common values between two arrays?

X = np.random.randint(0,20,20)
Z = np.random.randint(0,20,20)
print(np.intersect1d(X,Z))


[ 0  2  5  6  7 10 12 18]


In [51]:
# 31. How to ignore all numpy warnings (not recommended)?

with np.errstate(all="ignore"):
    np.arange(3) / 0

In [52]:
# 32. Is the following expressions true? 

np.sqrt(-1) == np.emath.sqrt(-1)

False

In [54]:
# 33. How to get the dates of yesterday, today and tomorrow?

yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

In [56]:
# 34. How to get all the dates corresponding to the month of July 2016?


X = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(X)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [59]:
# 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [60]:
# 36. Extract the integer part of a random array of positive numbers using 4 different methods


Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[2. 5. 7. 0. 7. 0. 5. 5. 8. 0.]
[2. 5. 7. 0. 7. 0. 5. 5. 8. 0.]
[2. 5. 7. 0. 7. 0. 5. 5. 8. 0.]
[2 5 7 0 7 0 5 5 8 0]
[2. 5. 7. 0. 7. 0. 5. 5. 8. 0.]


In [61]:
# 37. Create a 5x5 matrix with row values ranging from 0 to 4 

X = np.zeros((5,5))
X += np.arange(5)
print(X)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [62]:
# 38. Consider a generator function that generates 10 integers and use it to build an array


def generate():
    for x in range(10):
        yield x
X = np.fromiter(generate(),dtype=float,count=-1)
print(X)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [64]:
# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded


Y = np.linspace(0,1,11,endpoint=False)[1:]
print(Y)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [65]:
# 40. Create a random vector of size 10 and sort it 

Z = np.random.random(10)
Z.sort()
print(Z)

[0.21583278 0.22139541 0.45977689 0.48267271 0.4842565  0.58544038
 0.60326132 0.68643985 0.86520153 0.96001145]


In [66]:
# 41. How to sum a small array faster than np.sum?


Z = np.arange(10)
np.add.reduce(Z)

45

In [71]:
# 42. Consider two random array A and B, check if they are equal

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


In [75]:
# 43. Make an array immutable (read-only)

Z = np.zeros(10)
Z.flags.writeable = False
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [76]:
# 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates


Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.42342015 0.63536379 0.47528799 0.75707119 0.96659532 0.59256026
 0.73183321 0.88240252 0.85846274 1.05309798]
[0.97127169 1.22545087 1.53156985 0.36952355 1.32750184 1.30796628
 1.14570722 1.33118737 1.40995768 1.09659616]


In [77]:
# 45. Create random vector of size 10 and replace the maximum value by 0 


Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.         0.25071465 0.11141309 0.55276027 0.49177985 0.16090546
 0.65274596 0.00670602 0.85720838 0.47937309]


In [3]:
# 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

import numpy as np
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [4]:
# 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))


X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


In [5]:
# 48. Print the minimum and maximum representable value for each numpy scalar type


for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [6]:
# 49. How to print all the values of an array?

np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
# 50. How to find the closest value (to a given scalar) in a vector?



Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

28


In [ ]:
# 51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [9]:
# 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances


Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.99991016 0.35291731 0.47696643 0.58991753 0.60576314
  0.19670187 0.33630952 0.6310963  0.39227014]
 [0.99991016 0.         0.91936127 0.58997075 0.55016519 0.50043374
  1.18585088 0.66773669 0.86005315 0.74418764]
 [0.35291731 0.91936127 0.         0.33080688 0.38634806 0.42796581
  0.41145326 0.41518358 0.28614571 0.17554269]
 [0.47696643 0.58997075 0.33080688 0.         0.12146007 0.12879731
  0.63407361 0.25135162 0.37034942 0.15531062]
 [0.58991753 0.55016519 0.38634806 0.12146007 0.         0.05235021
  0.73530082 0.36873516 0.32788055 0.22362474]
 [0.60576314 0.50043374 0.42796581 0.12879731 0.05235021 0.
  0.76030788 0.35758324 0.37992194 0.2588445 ]
 [0.19670187 1.18585088 0.41145326 0.63407361 0.73530082 0.76030788
  0.         0.52958968 0.69486535 0.51727299]
 [0.33630952 0.66773669 0.41518358 0.25135162 0.36873516 0.35758324
  0.52958968 0.         0.58137454 0.29762408]
 [0.6310963  0.86005315 0.28614571 0.37034942 0.32788055 0.37992194
  0.69486535 0.58137

In [11]:
# 53. How to convert a float (32 bits) array into an integer (32 bits) in place?


Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[21 25 26 89 41 39 99 79 96 25]


In [ ]:
# 54. How to read the following file?

In [12]:
# 55. What is the equivalent of enumerate for numpy arrays?


Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [13]:
# 56. Generate a generic 2D Gaussian-like array


X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [14]:
# 57. How to randomly place p elements in a 2D array? 

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [4]:
# 58. Subtract the mean of each row of a matrix

import numpy as np
X = np.random.rand(5, 10)

Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.01915606 -0.08497465 -0.21705914 -0.10057779  0.48742692 -0.35452926
   0.07646727  0.17059021 -0.21844133  0.26025382]
 [ 0.0097484   0.40625026  0.3964019  -0.07719754 -0.46644956 -0.45312005
  -0.09375504  0.06108727  0.27197981 -0.05494546]
 [-0.04573774  0.32146746  0.13803515  0.01616505  0.17120972 -0.48982512
  -0.21691934  0.26614067 -0.23537231  0.07483645]
 [-0.37137223 -0.07865424  0.10913058 -0.41881111  0.32808105  0.16700203
   0.01733435  0.16889058 -0.35584339  0.43424239]
 [-0.25364737 -0.00057536  0.10639656  0.03736559  0.19598293  0.35183475
   0.35137914 -0.36634835 -0.02960236 -0.39278552]]


In [5]:
# 59. How to sort an array by the nth column?


Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[1 6 8]
 [5 1 4]
 [6 9 8]]
[[5 1 4]
 [1 6 8]
 [6 9 8]]


In [6]:
# 60. How to tell if a given 2D array has null columns?


Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [8]:
# 61. Find the nearest value from a given value in an array

Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5658805326990539


In [9]:
# 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?


A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [10]:
# 63. Create an array class that has a name attribute

class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [11]:
# 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 4. 3. 2. 2. 3. 4. 3. 3. 3.]


In [12]:
# 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?


X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [13]:
# 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors


w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


In [14]:
# 67. Considering a four dimensions array, how to get sum over the last two axis at once?

A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes 
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[69 58 72 51]
 [63 64 64 58]
 [64 37 51 34]]
[[69 58 72 51]
 [63 64 64 58]
 [64 37 51 34]]


In [15]:
# 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices?


D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.50498457 0.57672884 0.50710161 0.47902395 0.47671047 0.58695921
 0.45166078 0.49164214 0.35939289 0.45630446]


In [16]:
# 69. How to get the diagonal of a dot product?

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))


np.diag(np.dot(A, B))

array([2.66984092, 0.45775974, 1.49427199, 1.78344655, 1.39580564])

In [17]:
# 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?


Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [18]:
# 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? 

A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [19]:
# 72. How to swap two rows of an array?


A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [20]:
# 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 2,  6) ( 2, 16) ( 2, 41) ( 2, 80) ( 3, 55) ( 3, 94) ( 6, 80) (11, 60)
 (11, 82) (16, 34) (16, 41) (16, 99) (18, 35) (18, 42) (18, 51) (18, 86)
 (31, 41) (31, 77) (34, 99) (35, 86) (39, 49) (39, 95) (41, 77) (42, 51)
 (45, 49) (45, 87) (49, 87) (49, 95) (55, 94) (60, 82)]


In [21]:
# 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? 

C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [22]:
# 75. How to compute averages using a sliding window over an array?

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [23]:
# 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])

from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [24]:
# 77. How to negate a boolean, or to change the sign of a float inplace?

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.45982746, -0.49196788,  0.33320639, -0.42625423, -0.49389723,
        0.92525537, -0.92380163, -0.72639102,  0.50204325,  0.0345302 ,
        0.74756179, -0.03122858,  0.46902952, -0.36423769,  0.00982906,
       -0.94255671,  0.99963934,  0.45527392,  0.90260924, -0.42313699,
        0.49595495, -0.18183222, -0.59969874,  0.43444589, -0.22066288,
        0.70864943, -0.54214193,  0.61808065, -0.10652659, -0.87509557,
       -0.6185515 ,  0.58623038,  0.63216903,  0.71170334, -0.93777611,
        0.31092764, -0.39718194,  0.13365068,  0.83685724, -0.30719739,
        0.70415416,  0.66839746,  0.01405192, -0.5381459 , -0.45683247,
       -0.78559723, -0.28191254, -0.93821182, -0.17167874, -0.29944998,
       -0.52695842, -0.86029248,  0.84540984,  0.16560241,  0.97615285,
        0.64698759,  0.53834531,  0.96980832, -0.58787762, -0.47746641,
        0.95218629, -0.84905884, -0.31786288,  0.39893183,  0.84089613,
        0.05259086,  0.46402906, -0.74816203, -0.86533928, -0.40

In [25]:
# 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? 



def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 3.14464754  3.17741827  0.30749376 10.18532963  5.16236416  7.94377981
  8.87094354 15.68141225  9.80560323 14.63600092]


In [26]:
# 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?


P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 9.80923744  1.90020503  1.58741127  7.02115479  2.9486492   7.97029138
   8.67780506  9.89129371  5.60147706  9.08224888]
 [ 2.47401428  5.42942881  8.82134817 13.25721307  3.27586522  4.71066535
   1.38249306 14.40040184  6.53508212  2.52284359]
 [ 0.58125319  3.49872278 13.03153522  4.97135569 12.91338953 10.1387487
   3.75264424  1.87901253  9.49122582  5.6047658 ]
 [12.08364728  5.86061712  0.25018695  1.40187789  2.68153398  4.41196
  12.77155397  3.61670131  0.24707968  9.28889634]
 [ 7.51639321  3.13842902  4.69636365  1.26307945  8.51050542  2.6031733
  10.22783995  1.10328757  5.73160413  3.21093149]
 [ 2.28245862  4.91905612 14.77640616  5.80710123 13.75334185 11.65159726
   2.36412122  2.11698362 10.19557062  7.42872085]
 [ 4.37043215  1.74601275  7.3807133   7.73936071  2.66735761  0.71172566
   5.20960586  8.06718768  0.40292247  2.28244756]
 [14.37437906 10.38355153  1.97267749  5.42409643 10.10174249  0.61782443
  17.47434564  4.24612751  7.8968342   8.91878849]
 [15.

In [ ]:
# 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary)



In [28]:
# 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [29]:
# 82. Compute a matrix rank


Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
print(rank)

10


In [30]:
# 83. How to find the most frequent value in an array?

Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())


9


In [31]:
# 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)


[[[[3 2 2]
   [1 1 4]
   [2 2 2]]

  [[2 2 2]
   [1 4 2]
   [2 2 4]]

  [[2 2 1]
   [4 2 2]
   [2 4 0]]

  [[2 1 2]
   [2 2 1]
   [4 0 4]]

  [[1 2 3]
   [2 1 1]
   [0 4 2]]

  [[2 3 2]
   [1 1 2]
   [4 2 2]]

  [[3 2 3]
   [1 2 3]
   [2 2 3]]

  [[2 3 3]
   [2 3 2]
   [2 3 4]]]


 [[[1 1 4]
   [2 2 2]
   [3 2 1]]

  [[1 4 2]
   [2 2 4]
   [2 1 2]]

  [[4 2 2]
   [2 4 0]
   [1 2 0]]

  [[2 2 1]
   [4 0 4]
   [2 0 0]]

  [[2 1 1]
   [0 4 2]
   [0 0 3]]

  [[1 1 2]
   [4 2 2]
   [0 3 2]]

  [[1 2 3]
   [2 2 3]
   [3 2 0]]

  [[2 3 2]
   [2 3 4]
   [2 0 2]]]


 [[[2 2 2]
   [3 2 1]
   [1 0 1]]

  [[2 2 4]
   [2 1 2]
   [0 1 2]]

  [[2 4 0]
   [1 2 0]
   [1 2 2]]

  [[4 0 4]
   [2 0 0]
   [2 2 1]]

  [[0 4 2]
   [0 0 3]
   [2 1 0]]

  [[4 2 2]
   [0 3 2]
   [1 0 4]]

  [[2 2 3]
   [3 2 0]
   [0 4 4]]

  [[2 3 4]
   [2 0 2]
   [4 4 4]]]


 [[[3 2 1]
   [1 0 1]
   [1 1 4]]

  [[2 1 2]
   [0 1 2]
   [1 4 4]]

  [[1 2 0]
   [1 2 2]
   [4 4 0]]

  [[2 0 0]
   [2 2 1]
   [4 0 4]]

  [[0 0 3]
   

In [32]:
# 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] 

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 3 11 18 17  8]
 [11  0 10  5 10]
 [18 10  2 42  0]
 [17  5 42  6  8]
 [ 8 10  0  8  5]]


In [33]:
# 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))

p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [34]:
# 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [35]:
# 88. How to implement the Game of Life using numpy arrays?

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [36]:
# 89. How to get the n largest values of an array

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5


print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


In [37]:
# 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)


def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [38]:
# 91. How to create a record array from a regular array?


Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [40]:
# 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods


1.17 s ± 40.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
199 ms ± 5.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
142 ms ± 4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [42]:
# 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 4 6 7]


In [43]:
# 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

Z = np.random.randint(0,5,(10,3))
print(Z)

[[2 4 3]
 [4 2 3]
 [1 3 1]
 [0 0 4]
 [2 2 3]
 [0 3 4]
 [3 1 0]
 [4 1 0]
 [1 1 4]
 [1 4 2]]


In [44]:
# 95. Convert a vector of ints into a matrix binary representation

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [45]:
# 96. Given a two dimensional array, how to extract unique rows?

uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 4]
 [0 3 4]
 [1 1 4]
 [1 3 1]
 [1 4 2]
 [2 2 3]
 [2 4 3]
 [3 1 0]
 [4 1 0]
 [4 2 3]]


In [47]:
# 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)

array([[0.06221151, 0.07510036, 0.10641166, 0.06601638, 0.09378977,
        0.02874008, 0.02542406, 0.11506309, 0.08172946, 0.09691747],
       [0.22129077, 0.26713732, 0.37851385, 0.23482495, 0.33361689,
        0.1022305 , 0.09043519, 0.40928759, 0.29071752, 0.34474233],
       [0.18391747, 0.22202109, 0.31458749, 0.19516589, 0.27727307,
        0.08496502, 0.07516179, 0.34016392, 0.24161888, 0.28651956],
       [0.03524648, 0.04254878, 0.06028847, 0.03740217, 0.05313743,
        0.01628295, 0.01440423, 0.06519002, 0.04630455, 0.05490945],
       [0.48177359, 0.5815864 , 0.82406498, 0.51123894, 0.72631951,
        0.2225667 , 0.19688704, 0.89106269, 0.63292302, 0.75054078],
       [0.0590838 , 0.07132466, 0.10106177, 0.06269738, 0.08907445,
        0.02729516, 0.02414585, 0.10927824, 0.07762048, 0.0920449 ],
       [0.40048628, 0.48345817, 0.68502452, 0.42498009, 0.60377116,
        0.18501411, 0.16366725, 0.74071803, 0.526133  , 0.62390569],
       [0.30100422, 0.36336563, 0.5148622

In [49]:
# 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

In [50]:
# 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.


X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [51]:
# 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).

X = np.random.randn(100) 
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.22109556  0.16456827]
